model:
  name: 'resnet50_fc512'

data:
  type: 'image'
  root: 'datasets' # SoccerNet train/test/valid/challenge sets will be downloaded under '/path/to/project/datasets/soccernetv3/reid/'
  height: 320
  width: 160
  workers: 8
  transforms: ['random_flip', 'random_crop', 'random_rotation', 'color_jitter', 'random_erase']
  sources: ['soccernetv3']
  targets: ['soccernetv3']
  # training and validation sets are in the 'soccernetv3' dataset
  # test set is in the 'soccernetv3_test' dataset
  # challenge set is in the 'soccernetv3_challenge' dataset

soccernetv3:
  training_subset: 1.0

sampler:
  train_sampler: RandomActionIdentitySampler
  train_sampler_t: RandomActionIdentitySampler
  num_instances: 4
  num_actions: 8

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 0.2
    weight_x: 1.0
    action_aware: True
    warmup_epochs: 5

train:
  batch_size: 128
  print_freq: 10
  checkpoint_freq: 1
  max_epoch: 60
  lr_scheduler: cosine

test:
  batch_size: 128
  dist_metric: cosine
  normalize_feature: True
  ranks: [1, 5, 10]
  start_eval: 5
  eval_freq: 5
  export_ranking_results: False
