model:
  name: 'resnet50_fc512'

data:
  type: 'image'
  root: 'datasets'
  save_dir: 'log/soccernetv3_smoke'
  height: 320
  width: 160
  workers: 8
  transforms: ['random_flip', 'random_crop', 'random_rotation', 'color_jitter', 'random_erase']
  sources: ['soccernetv3']
  targets: ['soccernetv3']

soccernetv3:
  training_subset: 0.01

sampler:
  train_sampler: RandomActionIdentitySampler
  train_sampler_t: RandomActionIdentitySampler
  num_instances: 4
  num_actions: 8

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 0.5
    weight_x: 0.5
    action_aware: True
    warmup_epochs: 0

train:
  batch_size: 128
  print_freq: 10
  checkpoint_freq: 1
  max_epoch: 2
  lr_scheduler: cosine

test:
  batch_size: 128
  dist_metric: cosine
  normalize_feature: True
  ranks: [1, 5, 10]
  start_eval: 5
  eval_freq: 5
  export_ranking_results: False
